export { default as authRoutes } from './auth'
export { default as postRoutes } from './posts'
export { default as userRoutes } from './testUserRoute'
export { default as uploadRoutes } from './upload'
export { default as commentRoutes } from './comments'
