export { default as authRoutes } from './auth'
export { default as postRoutes } from './posts'
export { default as uploadRoutes } from './upload'
export { default as commentRoutes } from './comments'
export { default as userRoutes } from './users'
export { default as likeRoutes } from './likes'
