export { Footer } from './footerCmp'
export { Header } from './header'
export { ProtectedRoute } from './protectedRoute'
export { Share } from './share'
export { Posts } from './posts'
export { PostCard } from './postCardCmp'
